// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace SBSC_Store.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1409),
                            Description = "Books Category",
                            Name = "Books",
                            UpdatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1411)
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CreatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1413),
                            Description = "Music Category",
                            Name = "Music",
                            UpdatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1414)
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ProductId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1720),
                            Description = "The Intellectual Life of the catholic scholar",
                            ImageUrl = "",
                            Name = "The Intellectual Life",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1721)
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            CategoryId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CreatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1725),
                            Description = "Fair Game 1992",
                            ImageUrl = "",
                            Name = "Fair Game",
                            Price = 2000m,
                            UpdatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1725)
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1728),
                            Description = "Les Sources by Pere Gratry",
                            ImageUrl = "",
                            Name = "Les Sources",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2026, 4, 10, 23, 36, 8, 987, DateTimeKind.Utc).AddTicks(1729)
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
